---
# This playbook will install terraform

- name: Install dependencies for terraform
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - unzip

- name: Unarchive file terraform zip
  unarchive:
    src: "{{ terraform_release_url }}"
    dest: /usr/local/bin
    remote_src: yes
