---
# This playbook set full provision for server

- name: Setup provision
  hosts: localhost
  remote_user: root
  become: true
  roles:
    - ssh
    - terraform
    - docker
    - k8s
  environment:
    KUBECONFIG: "{{ k8s_config_path }}"